name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
branches:
  - 'master'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
exclude-labels:
  - 'skip-changelog'
change-template: '* $TITLE @$AUTHOR (#$NUMBER)'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '.github/*'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
category-template: '### $TITLE'
template: |
  ## Changes

  $CHANGES
