name: Default Branch

on:
  push:
    branches:
    - main

jobs:
  test-master:
    runs-on: elisa-normal
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      env:
        GOLANGCI_LINT_FLAGS: --out-format=github-actions
      run: mage lint

    - name: Run test
      run: mage unittest

    - name: Upload test coverage to codecov
      uses: elisa-actions/codecov-action@v4-elisa
      with:
        url: https://codecov.csf.elisa.fi

    - uses: elisa-actions/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        disable-releaser: false
        disable-autolabeler: true

  build-packages:
    runs-on: elisa-normal
    timeout-minutes: 30
    needs: test-master
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Build packages
      run: mage buildSubset

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} release [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) build failed."
      run: send-to-mattermost
