name: Default Branch

on:
  push:
    branches:
    - main

jobs:
  test-master:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: 1.18.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Run test
      run: |
        make test

    - uses: elisa-actions/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        disable-releaser: false
        disable-autolabeler: true

  build-linux-package:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 30
    needs: test-master
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: 1.18.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package linux binaries
      run: |
        make build-package-linux-amd64

  build-windows-package:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 30
    needs: test-master
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: 1.18.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package windows binaries
      run: |
        make build-package-windows

  build-darwin-amd64-package:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 30
    needs: test-master
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: 1.18.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package darwin amd64 binaries
      run: |
        make build-package-darwin-amd64

  build-darwin-arm64-package:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 30
    needs: test-master
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: 1.18.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package darwin arm64 binary
      run: |
        make build-package-darwin-arm64
