name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  build:
    runs-on: elisa-normal
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      env:
        GOLANGCI_LINT_FLAGS: --out-format=github-actions
      run: mage lint

    - name: Run test
      run: mage unittest

    - name: Upload test coverage to codecov
      uses: elisa-actions/codecov-action@v4-elisa
      with:
        url: https://codecov.csf.elisa.fi

    - name: Build packages
      run: mage buildSubset

    - name: Notify failure
      if: |
        github.event.pull_request.draft == false &&
        failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} PR build. Please check [here](${{ github.event.pull_request.html_url }}/checks)."
      run: send-to-mattermost

  automerge:
    needs: [build]
    permissions:
      pull-requests: write
      contents: write
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ secrets.DOPS_SRE_PAT }}
