name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  build:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: 1.18.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Run test
      run: |
        make test

    - name: Build golang binary
      run: |
        make build

  automerge:
    needs: [build]
    permissions:
      pull-requests: write
      contents: write
    runs-on:
      - self-hosted
      - kaas
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
