name: Release

on:
  release:
    types:
    - published

jobs:
  test-release:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Run test
      run: |
        make test

  publish-linux-package:
    runs-on: self-hosted
    timeout-minutes: 30
    needs: test-release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package linux binaries
      run: |
        make build-package-linux-amd64

    - name: Upload Linux binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/resource-advisor-linux-amd64
          bin/linux-amd64-sha256sum.txt

  publish-windows-package:
    runs-on: self-hosted
    timeout-minutes: 30
    needs: test-release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package windows binaries
      run: |
        make build-package-windows

    - name: Upload windows binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/resource-advisor-windows
          bin/windows-sha256sum.txt

  publish-darwin-amd64-package:
    runs-on: self-hosted
    timeout-minutes: 30
    needs: test-release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package darwin amd64 binaries
      run: |
        make build-package-darwin-amd64

    - name: Upload MacOS amd64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/resource-advisor-darwin-amd64
          bin/darwin-amd64-sha256sum.txt

  publish-darwin-arm64-package:
    runs-on: self-hosted
    timeout-minutes: 30
    needs: test-release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Run ensure
      run: |
        make deps
        make ensure

    - name: Build and package darwin arm64 binary
      run: |
        make build-package-darwin-arm64

    - name: Upload MacOS arm64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/resource-advisor-darwin-arm64
          bin/darwin-arm64-sha256sum.txt
