name: Release

on:
  release:
    types:
    - published

jobs:
  test-release:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Retrieve Go version
      run: echo "GO_VERSION=$(make go-version)" >> $GITHUB_OUTPUT
      id: version

    - uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.version.outputs.GO_VERSION }}

    - name: Run ensure
      run: make go-ensure

    - name: Run lint
      run: make go-lint

    - name: Run test
      run: make go-unit-test

  build-and-publishpackages:
    runs-on:
    - self-hosted
    - kaas
    timeout-minutes: 30
    needs: test-release
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Retrieve Go version
      run: echo "GO_VERSION=$(make go-version)" >> $GITHUB_OUTPUT
      id: version

    - uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.version.outputs.GO_VERSION }}

    - name: Run ensure
      run: go-ensure

    - name: Build and package binaries
      run: make build-subset

    - name: Upload Linux binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/linux/amd64/**

    - name: Upload windows binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/windows/amd64/**

    - name: Upload MacOS amd64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/darwin/amd64/**

    - name: Upload MacOS arm64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/darwin/arm64/**

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} release [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) build failed."
      run: send-to-mattermost

