name: Release

on:
  release:
    types:
    - published

jobs:
  test-release:
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      run: mage go:lint

    - name: Run test
      run: mage go:unitTest

  build-and-publish-packages:
    runs-on: elisa-normal
    timeout-minutes: 30
    needs: test-release
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      run: mage go:lint

    - name: Run test
      run: mage go:unitTest

    - name: Upload test coverage to codecov
      uses: elisa-actions/codecov-action@v4-elisa
      with:
        url: https://codecov.csf.elisa.fi

    - name: Build packages
      run: mage go:crossBuild

    - name: Upload Linux amd64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/linux/amd64/**

    - name: Upload Linux arm64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/linux/arm64/**

    - name: Upload windows binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/windows/amd64/**

    - name: Upload MacOS amd64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/darwin/amd64/**

    - name: Upload MacOS arm64 binary & checksum
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/bin/darwin/arm64/**

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} release [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) build failed."
      run: send-to-mattermost

